<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UpdateEventWithSystemTime" Id="{7b248580-b99c-4232-8aaf-016fef871369}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventWithSystemTime 
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	stFileTime: T_FILETIME;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME( timeLoDW => stFileTime.dwLowDateTime,
	              timeHiDW => stFileTime.dwHighDateTime);


stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);				  ]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>